services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes:  
      - ./src/:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
    networks:
      - wpsite
  

  cli:
    image: wordpress:cli
    volumes:
      - ./src/:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      # Tăng PHP memory limit cho WP-CLI (mặc định 128M không đủ khi extract WP Core)
      WP_CLI_PHP_ARGS: -d memory_limit=512M
    depends_on:
      - db
    networks:
      - wpsite
  # Hide temporary
  # cf-tunnel:
  #   image: cloudflare/cloudflared:latest
  #   restart: always
  #   command: tunnel --url http://wordpress:80
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - wpsite
  

networks:
  wpsite:
  
volumes:
  db_data: