server {
    listen 80;
    listen [::]:80;
    server_name hkt-fashion.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name hkt-fashion.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/hkt-fashion.duckdns.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hkt-fashion.duckdns.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        proxy_pass http://127.0.0.1:8000; # Trỏ ngược vào container WordPress trong Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Tối ưu hóa upload file dung lượng lớn (ảnh sản phẩm)
        client_max_body_size 64M;
    }
}
